export type EmojiEntry = { char: string; keywords: string[] }

export const EMOJI_GROUPS: Record<string, EmojiEntry[]> = {
    'Smileys & People': [
        { char: '😀', keywords: ['happy', 'smile', 'grin'] },
        { char: '😃', keywords: ['happy', 'smile', 'open'] },
        { char: '😄', keywords: ['happy', 'smile', 'laugh'] },
        { char: '😁', keywords: ['grin', 'beam'] },
        { char: '😂', keywords: ['laugh', 'joy', 'tears'] },
        { char: '🤣', keywords: ['rolling', 'laugh', 'floor'] },
        { char: '😅', keywords: ['sweat', 'nervous', 'relief'] },
        { char: '😆', keywords: ['laugh', 'squint'] },
        { char: '😊', keywords: ['blush', 'happy', 'warm'] },
        { char: '😇', keywords: ['angel', 'innocent', 'halo'] },
        { char: '🙂', keywords: ['slight', 'smile'] },
        { char: '😉', keywords: ['wink'] },
        { char: '😍', keywords: ['love', 'heart', 'eyes'] },
        { char: '🥰', keywords: ['love', 'hearts', 'adore'] },
        { char: '😘', keywords: ['kiss', 'love', 'blow'] },
        { char: '😎', keywords: ['cool', 'sunglasses'] },
        { char: '🤓', keywords: ['nerd', 'glasses', 'smart'] },
        { char: '🧐', keywords: ['monocle', 'curious'] },
        { char: '🤔', keywords: ['think', 'hmmm', 'ponder'] },
        { char: '🤗', keywords: ['hug', 'warm', 'open'] },
        { char: '🤩', keywords: ['star', 'amazed', 'excited'] },
        { char: '🥳', keywords: ['party', 'celebrate', 'birthday'] },
        { char: '😏', keywords: ['smirk', 'sly'] },
        { char: '😴', keywords: ['sleep', 'tired', 'zzz'] },
        { char: '🥺', keywords: ['please', 'beg', 'puppy'] },
        { char: '😤', keywords: ['angry', 'huff', 'frustrated'] },
        { char: '😈', keywords: ['devil', 'evil', 'mischief'] },
        { char: '👻', keywords: ['ghost', 'boo', 'spooky'] },
        { char: '💀', keywords: ['skull', 'dead', 'rip'] },
        { char: '🤡', keywords: ['clown', 'funny'] },
        { char: '👽', keywords: ['alien', 'ufo', 'space'] },
        { char: '🤖', keywords: ['robot', 'bot', 'ai'] },
        { char: '👾', keywords: ['alien', 'monster', 'game', 'space invader'] },
        { char: '🥷', keywords: ['ninja', 'stealth', 'shadow'] },
        { char: '🧙', keywords: ['wizard', 'magic', 'mage'] },
        { char: '🦸', keywords: ['hero', 'superhero', 'cape'] },
        { char: '🧛', keywords: ['vampire', 'dracula'] },
    ],
    'Gestures & Body': [
        { char: '👍', keywords: ['thumbs up', 'like', 'yes'] },
        { char: '👎', keywords: ['thumbs down', 'dislike', 'no'] },
        { char: '👋', keywords: ['wave', 'hello', 'bye'] },
        { char: '🤞', keywords: ['crossed', 'luck', 'hope'] },
        { char: '🤟', keywords: ['love', 'rock', 'hand'] },
        { char: '🤘', keywords: ['rock', 'metal', 'horns'] },
        { char: '👏', keywords: ['clap', 'bravo', 'applause'] },
        { char: '🙌', keywords: ['raise', 'celebrate', 'hands'] },
        { char: '💪', keywords: ['strong', 'muscles', 'flex'] },
        { char: '🫡', keywords: ['salute', 'respect'] },
        { char: '🫶', keywords: ['heart', 'hands', 'love'] },
        { char: '👀', keywords: ['eyes', 'look', 'see'] },
        { char: '👤', keywords: ['user', 'person', 'account'] },
        { char: '👥', keywords: ['users', 'group', 'team'] },
    ],
    'Animals & Nature': [
        { char: '🐶', keywords: ['dog', 'puppy', 'pet'] },
        { char: '🐱', keywords: ['cat', 'kitten', 'pet'] },
        { char: '🐻', keywords: ['bear', 'teddy'] },
        { char: '🦊', keywords: ['fox'] },
        { char: '🐼', keywords: ['panda', 'bear'] },
        { char: '🦁', keywords: ['lion', 'king'] },
        { char: '🐸', keywords: ['frog', 'toad'] },
        { char: '🐧', keywords: ['penguin', 'linux'] },
        { char: '🦄', keywords: ['unicorn', 'magic'] },
        { char: '🐉', keywords: ['dragon', 'fire'] },
        { char: '🦅', keywords: ['eagle', 'bird', 'freedom'] },
        { char: '🦈', keywords: ['shark', 'ocean'] },
        { char: '🐙', keywords: ['octopus', 'tentacle'] },
        { char: '🦋', keywords: ['butterfly', 'nature'] },
        { char: '🌸', keywords: ['blossom', 'flower', 'spring'] },
        { char: '🌺', keywords: ['flower', 'hibiscus'] },
        { char: '🌻', keywords: ['sunflower', 'sun'] },
        { char: '🌲', keywords: ['tree', 'evergreen', 'pine'] },
        { char: '🍀', keywords: ['clover', 'luck', 'irish'] },
        { char: '🌊', keywords: ['wave', 'ocean', 'water'] },
    ],
    'Food & Drink': [
        { char: '🍕', keywords: ['pizza', 'food', 'slice'] },
        { char: '🍔', keywords: ['burger', 'hamburger', 'food'] },
        { char: '🍟', keywords: ['fries', 'chips'] },
        { char: '🌮', keywords: ['taco', 'mexican'] },
        { char: '🍣', keywords: ['sushi', 'japanese', 'fish'] },
        { char: '🍿', keywords: ['popcorn', 'snack', 'movie'] },
        { char: '🍩', keywords: ['donut', 'doughnut', 'sweet'] },
        { char: '🍪', keywords: ['cookie', 'sweet'] },
        { char: '🎂', keywords: ['cake', 'birthday'] },
        { char: '🍫', keywords: ['chocolate', 'candy'] },
        { char: '🍺', keywords: ['beer', 'drink', 'cheers'] },
        { char: '🧋', keywords: ['boba', 'tea', 'bubble'] },
        { char: '🍷', keywords: ['wine', 'drink', 'glass'] },
        { char: '🥤', keywords: ['soda', 'drink', 'cup'] },
    ],
    'Activities & Sports': [
        { char: '🎮', keywords: ['game', 'play', 'gaming', 'controller'] },
        { char: '🎯', keywords: ['target', 'bullseye', 'dart'] },
        { char: '🎲', keywords: ['dice', 'game', 'luck'] },
        { char: '🎪', keywords: ['circus', 'show'] },
        { char: '🎵', keywords: ['music', 'note'] },
        { char: '🎸', keywords: ['guitar', 'rock', 'music'] },
        { char: '🎧', keywords: ['headphones', 'music', 'listen'] },
    ],
    'Travel & Objects': [
        { char: '🚀', keywords: ['rocket', 'launch', 'fast', 'space'] },
        { char: '🛸', keywords: ['ufo', 'alien', 'space'] },
        { char: '🏠', keywords: ['house', 'home'] },
        { char: '🏰', keywords: ['castle', 'kingdom'] },
        { char: '🎬', keywords: ['movie', 'action', 'film', 'clapperboard'] },
        { char: '📺', keywords: ['tv', 'show', 'television'] },
        { char: '📱', keywords: ['phone', 'mobile', 'smartphone'] },
        { char: '💻', keywords: ['laptop', 'computer', 'tech'] },
        { char: '📸', keywords: ['camera', 'photo', 'picture'] },
        { char: '📻', keywords: ['radio', 'audio'] },
        { char: '🔭', keywords: ['telescope', 'space', 'stars'] },
        { char: '🔬', keywords: ['microscope', 'science', 'lab'] },
        { char: '💡', keywords: ['idea', 'light', 'bulb'] },
        { char: '🔑', keywords: ['key', 'locked', 'auth'] },
        { char: '🧲', keywords: ['magnet', 'attract'] },
        { char: '🔒', keywords: ['lock', 'secure', 'private'] },
        { char: '📦', keywords: ['package', 'box', 'delivery'] },
        { char: '💾', keywords: ['disk', 'save', 'floppy'] },
    ],
    'Symbols & Hearts': [
        { char: '❤️', keywords: ['heart', 'love', 'red'] },
        { char: '🧡', keywords: ['heart', 'orange'] },
        { char: '💛', keywords: ['heart', 'yellow'] },
        { char: '💚', keywords: ['heart', 'green'] },
        { char: '💙', keywords: ['heart', 'blue'] },
        { char: '💜', keywords: ['heart', 'purple'] },
        { char: '🖤', keywords: ['heart', 'black'] },
        { char: '🤍', keywords: ['heart', 'white'] },
        { char: '💖', keywords: ['heart', 'sparkle'] },
        { char: '🌟', keywords: ['star', 'glow', 'shine'] },
        { char: '✨', keywords: ['sparks', 'magic', 'new', 'sparkle'] },
        { char: '🔥', keywords: ['fire', 'hot', 'trending', 'flame'] },
        { char: '💎', keywords: ['diamond', 'gem', 'premium'] },
        { char: '💫', keywords: ['dizzy', 'star', 'shooting'] },
        { char: '🌀', keywords: ['spiral', 'vortex', 'sync'] },
        { char: '🌈', keywords: ['rainbow', 'color', 'pride'] },
        { char: '🌙', keywords: ['moon', 'night', 'crescent'] },
        { char: '🎭', keywords: ['theater', 'mask', 'drama'] },
        { char: '🎨', keywords: ['art', 'paint', 'color', 'palette'] },
        { char: '📍', keywords: ['pin', 'location'] },
        { char: '🏁', keywords: ['flag', 'finish', 'race'] },
        { char: '💯', keywords: ['hundred', 'perfect', 'score'] },
        { char: '✅', keywords: ['check', 'done', 'complete'] },
        { char: '❌', keywords: ['cross', 'no', 'wrong'] },
    ],
}
